### ISSUE TITLE
Example not working: Argument 'txt' must be a JSON string, URL or file.

### ISSUE THREAD

**Issue by cutterkom** [hrbrmstr/longurl#2]
I tried to use the package, but it failed both: Using my data as well as your example in the readme. 

The error message: 
`Error: Argument 'txt' must be a JSON string, URL or file.`

And additionally there is the following warning: 
`In FUN(X[[i]], ...) : Forbidden (HTTP 403).`

Any idea what I am doing wrong?

**Comment by hrbrmstr** [comment]
Hrm. It seems they went to a "pay for API access" model: http://pro.urlex.org/

I'll try to find another expansion service. Thx for the bug report

**Comment by hrbrmstr** [comment]
I just pushed a new version that no longer relies on API services. Please give it a test.

**Comment by cutterkom** [comment]
It's working. Thanks!
