### ISSUE TITLE
Subscript out of bound

### ISSUE THREAD

**Issue by fabiogiglietto** [hrbrmstr/longurl#3]
Hi :)
I'm attempting to unshort a set of urls but I keep getting this error on URLs such as

> library(longurl)
> expand_urls("https://t.co/7ErdC53Jvk")
Error in http_statuses[[as.character(status)]] : subscript out of bounds

We have analyzed in depth the issue and it depends on Linkedin and other websites blocking some ranges of ip addresses (e.g. ip from Amazon AWS and Google Platform). From some other ip the code works as expected (at last for a few time). Please see https://stackoverflow.com/questions/27231113/999-error-code-on-head-request-to-linkedin for details about the issue.

Since we are attempting to resolve about a million of short urls and this error stop the process without specifying the URL or saving the results already collected, I was wondering if there is a chance to catch this error in longurl code so that the URL is skipped with warnings as it happens with other types of errors.

Any help is more than welcome. Best, Fabio

**Comment by hrbrmstr** [comment]
Hrm… lemme see when I'll have time to test on an AWS box. That particular URL no longer resolves (and the code doesn't die, it produces a warning). Can you add the output of `sessionInfo()` to the issue as well?

**Comment by hrbrmstr** [comment]
Well, upon review, a test rly wasn't necessary. I'm not really sure what is causing your issue since the HEAD request was wrapped in `safely()` and that would have been the place the error showed up. However, there was one more `httr` call (to retrieve status) that _in theory_ _could_ have been messing up. I added a wrapper and tester for that as well.

**Comment by fabiogiglietto** [comment]
Thanks for your prompt reply.

In my attempts to debug expand_urls function I found the problem is the http status 999 returned by certain Urls like the one above. I tried again the same URL and I'm getting the same result both on Amazon AWS and Google Cloud Platform.

**Comment by fabiogiglietto** [comment]
Your update addressed the issue. Thank you!

**Comment by hrbrmstr** [comment]
Thx for the extra info! I can do a PR into `httr` that shld address this more generically.

**Comment by artistsm** [comment]
I am facing the same issue. Can you kindly tell me how you resolved the problem
