### ISSUE TITLE
Factors

### ISSUE THREAD

**Issue by JohnCoene** [hrbrmstr/longurl#4]
Just a suggestion because it took me a while to understand what was happening: throw a different error/warning when passing `factor`.

```
library(longurl)

long_urls <- expand_urls("http://t.co/D4C7aWYIiA") # works
expand_urls(as.factor("http://t.co/D4C7aWYIiA")) # invalid URL
> Invalid URL: [http://t.co/D4C7aWYIiA]
```

**Comment by hrbrmstr** [comment]
doh! thx for catching this! i'll just force a conversion to character.
